const NEWORDER = "NEWORDER";
const COMPLETED = "COMPLETED";
const DISPUTE = "DISPUTE";
const ORDERCANCELED = "ORDERCANCELED";

module.exports = {
  NEWORDER,
  COMPLETED,
  DISPUTE,
  ORDERCANCELED,
};
